#!/bin/sh

bspc monitor -d I II III IV V VI

bspc config border_width            2
bspc config window_gap              3
bspc config normal_border_color     "#282828"
bspc config active_border_color     "#ebdbb2"
bspc config focused_border_color    "#fe8019"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      false

# Rules
bspc rule -a 'Zathura'    state=tiled
bspc rule -a 'Emacs'     state=tiled

# autostart
#redshift &
feh --no-fehbg --bg-fill $HOME/dotfiles/wallpaper.png
sxhkd &
keepassxc &
dunst &
picom &
polybar main  &
