#!/bin/sh

bspc monitor -d I II III IV V VI

bspc config border_width            0
bspc config window_gap              8
bspc config normal_border_color     \"#31748f"
bspc config active_border_color     
bspc config focused_border_color    \"#9ccfd8"
bspc config presel_feedback_color   "$color6"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle	 true

# Rules
bspc rule -a 'Zathura'    state=tiled
bspc rule -a 'Emacs'     state=tiled

xset -dpms s off

# autostart
#redshift &
feh --no-fehbg --bg-fill $HOME/dotfiles/wallpaper.jpg
sxhkd &
keepassxc &
dunst &
picom &
polybar main  &
